# Imports and Installations

In [ ]:
#installations
!pip install bertopic
!pip install gensim

In [ ]:
#imports
import nltk
nltk.download('punkt_tab')

In [ ]:
#imports
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
import glob
import os
import gensim
from gensim.models.phrases import Phrases, Phraser
from gensim import corpora
from gensim.models import CoherenceModel
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
import re
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
import requests
import matplotlib.pyplot as plt
import random

In [ ]:
#Connecting to google drive
from google.colab import drive
drive.mount('/content/drive')

# Creating DF of transcriptions, corresponding file path, and file name

In [ ]:
# Define the base directory for the videos
base_dir = '/content/drive/MyDrive/Emergency_Meeting_Deepgram'

#Using glob to collect all the text files
file_paths = glob.glob(os.path.join(base_dir, '**', '*.txt'), recursive=True)

In [ ]:
#Creating a function to read the files
def read_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
        return content

In [ ]:
#Making a list of the documents where each index is a new transcription
documents = [read_file(fp) for fp in file_paths]

In [ ]:
#Creating the DF
df = pd.DataFrame({'file_path': file_paths, 'text': documents})

In [ ]:
#Creating a column for file names
file_names = []

#grabing the file name from the file path using REGEX
for path in df['file_path']:
    match = re.search(r'[^\\/]+$', path)
    file_name = match.group() if match else None
    file_names.append(file_name)

#Making the column in the df
df['file_name'] = file_names

df.head()

In [ ]:
#making snippet DF - needed for BERTopic model

#Function to make the chunked texts
def chunk_dataframe(df, max_chars=800): #each chunk with a max of 800 characters
    snippets = []

    for idx, row in df.iterrows():
        doc_id = row['file_name']

        #Getting rid of extra whitespace
        text = re.sub(r'\s+', ' ', row['text']).strip()

        #Splitting text into sentences
        sentences = sent_tokenize(text)

        #Initalizing string
        chunk, chunk_id = "", 0
        #Looping through each sentence
        for sentence in sentences:
            #Checking if adding this sentence will still stay in the max char limit
            if len(chunk) + len(sentence) <= max_chars:
                #Adding sentence to current chunk
                chunk += " " + sentence
            #Adding information to snippit list when the chunk reaches max char limit
            else:
                snippets.append({
                    'doc_id': doc_id,
                    'chunk_id': chunk_id,
                    'text': chunk.strip()
                })
                #Adding one to chunk id
                chunk_id += 1
                #starting new chunk
                chunk = sentence
        #Outside the loop if there are extra sentences
        if chunk:
            #Saving final sentences to list
            snippets.append({
                'doc_id': doc_id,
                'chunk_id': chunk_id,
                'text': chunk.strip()
            })
    #Returning data frame with chunk information
    return pd.DataFrame(snippets)

In [ ]:
#Chunking the df and saving it to a variable
chunked_df = chunk_dataframe(df)

,doc_id,chunk_id,text
0,the-matrix-attacks..txt,0,"Controversial influencer, Andrew Tape. Andrew ..."
1,the-matrix-attacks..txt,1,"Imagine shooting a man with your last bullet, ..."
2,the-matrix-attacks..txt,2,They fired the bullet that never fails. It bou...
3,the-matrix-attacks..txt,3,They need us and they use us. But the second w...
4,the-matrix-attacks..txt,4,Andrew tape is a self described miso is is thi...
...,...,...,...
11476,episode-100-tate-for-prime-minister.txt,188,Absolutely any entity that is not a world elec...
11477,episode-100-tate-for-prime-minister.txt,189,Any organization that tries to tell me what to...
11478,episode-100-tate-for-prime-minister.txt,190,This is the division. A Britain that is proud ...
11479,episode-100-tate-for-prime-minister.txt,191,If I become prime minister in two years or ten...
11480,episode-100-tate-for-prime-minister.txt,192,That is my guarantee that the British people. ...

# Preprosessing

In [ ]:
#creating a column that is lowercased
chunked_df['lower_text'] = chunked_df['text'].str.lower()

In [ ]:
#creating the stop words list using a list from github
stopwords_list = requests.get('https://gist.githubusercontent.com/rg089/35e00abf8941d72d419224cfd5b5925d/raw/12d899b70156fd0041fa9778d657330b024b959c/stopwords.txt').content
stop_words = set(stopwords_list.decode().splitlines())

In [ ]:
#creating custom stop words list for common filler words
custom_stopwords = stop_words.union({'gon', 'yeah', 'fucking','bro', 'shit','thing', 'wan','ha',
                                     'andrew', 'tate', 'person','year', 'day','lot','fuck',
                                     'doe', 'time', 'good', 'talk', 'gonna','people', 'things',
                                     'wanna'})
custom_stopwords=list(custom_stopwords)

#Initialzing the vectorizer
vectorizer = CountVectorizer(stop_words=custom_stopwords)

In [ ]:
#Tried out how it would look if the text was lemmatized - decided not to use it
import spacy
nlp = spacy.load('en_core_web_sm')

def lemmatize_text(text):
    doc = nlp(text)  # Process text with spaCy
    return " ".join([token.lemma_ for token in doc])  # Convert words to base form

#Adding the lemmatized text to the df
chunked_df['lemma_text'] = chunked_df['text'].apply(lemmatize_text)

In [ ]:
#creating the list of the text
documents = chunked_df['lower_text'].tolist()

#Tokenizing each sentence
tokenized_texts = [word_tokenize(text) for text in documents]

#Training bigram model to campure meaningful two word associations
bigram_model = Phrases(tokenized_texts, min_count=10, threshold=50)
bigram_phraser = Phraser(bigram_model)

#Applying bigram model to my dataset
processed_token_lists = [bigram_phraser[doc] for doc in tokenized_texts]

In [ ]:
#Convert processed tokens back into full sentences
processed_texts = [" ".join(tokens) for tokens in processed_token_lists]

#Making a new column with the bigram words
chunked_df['bigram_nolemmatext'] = processed_texts
#print(processed_texts)

In [ ]:
#saving for later
file_path = '/content/drive/MyDrive/Emergency_Meeting_Deepgram/chunked_df.csv'
chunked_df.to_csv(file_path, index=False)

In [ ]:
chunked_df.head()

,doc_id,chunk_id,text,lower_text,bigram_nolemmatext
0,the-matrix-attacks..txt,0,"Controversial influencer, Andrew Tape. Andrew ...","controversial influencer, andrew tape. andrew ...","controversial_influencer , andrew tape . andre..."
1,the-matrix-attacks..txt,1,"Imagine shooting a man with your last bullet, ...","imagine shooting a man with your last bullet, ...","imagine_shooting a man with your last_bullet ,..."
2,the-matrix-attacks..txt,2,They fired the bullet that never fails. It bou...,they fired the bullet that never fails. it bou...,they fired the bullet that never fails . it bo...
3,the-matrix-attacks..txt,3,They need us and they use us. But the second w...,they need us and they use us. but the second w...,they need us and they use us . but the second ...
4,the-matrix-attacks..txt,4,Andrew tape is a self described miso is is thi...,andrew tape is a self described miso is is thi...,andrew tape is a self described miso is is thi...

## Coherence Scores

Choosing the number of topics using coherence scores

In [ ]:
#Creating list of the documents
documents = chunked_df['bigram_nolemmatext'].tolist()

In [ ]:
#Preprocessing the the text
cleaned_docs = topic_model._preprocess_text(documents)

In [ ]:
#Initializing the analyzer
analyzer = topic_model.vectorizer_model.build_analyzer()
#Getting tokens
tokens = [analyzer(doc) for doc in cleaned_docs]

In [ ]:
#To reduce the impact of frequent words
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

In [ ]:
#Creating the dictionary
dictionary = corpora.Dictionary(tokens)
#Creating the corpus
corpus = [dictionary.doc2bow(token) for token in tokens]

In [ ]:
coherence_scores = []

#Running the model for topics ranging 3 to 30
for n_topics in range(3, 30):
    #Building the model
    model = BERTopic(embedding_model=embedding_model,
                       top_n_words=15,
                       vectorizer_model=vectorizer,
                       ctfidf_model=ctfidf_model,
                       umap_model=UMAP(n_neighbors=30, #Algorithm for reducing dimensional space
                                       n_components=2,
                                       metric='cosine',
                                       min_dist=0.0),
                       hdbscan_model=HDBSCAN(min_cluster_size=45, #Controlling the number of topics through the cluster model
                                             metric='euclidean',
                                             cluster_selection_method='eom',
                                             prediction_data=True))

    topics, _ = model.fit_transform(documents)
    model = model.reduce_topics(documents, nr_topics=n_topics)

    #Getting topic words per topic
    topic_words = [
        [word for word, _ in model.get_topic(topic_id)]
        for topic_id in model.get_topics().keys()
        if topic_id != -1 #not including the -1 topic because its the 'leftover' topic
    ]

    #Calculating coherence scores
    cm = CoherenceModel(
        topics=topic_words,
        texts=tokens,
        corpus=corpus,
        dictionary=dictionary,
        coherence='c_v'
    )
    #Getting coherence score
    score = cm.get_coherence()
    coherence_scores.append((n_topics, score))
    print(f"Topics: {n_topics}, Coherence: {score:.4f}")

Topics: 3, Coherence: 0.4604
Topics: 4, Coherence: 0.4635
Topics: 5, Coherence: 0.5925
Topics: 6, Coherence: 0.7565
Topics: 7, Coherence: 0.6576
Topics: 8, Coherence: 0.6233
Topics: 9, Coherence: 0.6768
Topics: 10, Coherence: 0.6763
Topics: 11, Coherence: 0.7240
Topics: 12, Coherence: 0.7247
Topics: 13, Coherence: 0.6825
Topics: 14, Coherence: 0.7250
Topics: 15, Coherence: 0.7126
Topics: 16, Coherence: 0.7161
Topics: 17, Coherence: 0.6725
Topics: 18, Coherence: 0.7217
Topics: 19, Coherence: 0.6957
Topics: 20, Coherence: 0.7228
Topics: 21, Coherence: 0.7086
Topics: 22, Coherence: 0.7152
Topics: 23, Coherence: 0.6191
Topics: 24, Coherence: 0.7357
Topics: 25, Coherence: 0.6294
Topics: 26, Coherence: 0.7161
Topics: 27, Coherence: 0.6673
Topics: 28, Coherence: 0.6580
Topics: 29, Coherence: 0.7145

In [ ]:
#Plotting the coherence score results
x, y = zip(*coherence_scores)
plt.plot(x, y, marker='o')
plt.xlabel('Number of Topics')
plt.ylabel('Coherence Score (c_v)')
plt.title('Topic Coherence for Topic Range 3–29')
plt.grid(True)
plt.show()

# Running the model

In [ ]:
#BERT model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
#building the model
topic_model = BERTopic(embedding_model=embedding_model,
                       top_n_words=15,
                       vectorizer_model=vectorizer,
                       ctfidf_model=ctfidf_model,
                       umap_model=UMAP(n_neighbors=30,
                                       n_components=2,
                                       metric='cosine',
                                       min_dist=0.0),
                       hdbscan_model=HDBSCAN(min_cluster_size=45,
                                             metric='euclidean',
                                             cluster_selection_method='eom',
                                             prediction_data=True))

#Running the model on the documents
topics, probs = topic_model.fit_transform(documents)

In [ ]:
#Saving the model
topic_model.save('/content/drive/MyDrive/Emergency_Meeting_Deepgram/Tate_model_sixtopics', save_embedding_model=True)

## Loading Saved Models

In [ ]:
topic_model = BERTopic.load('/content/drive/MyDrive/Emergency_Meeting_Deepgram/Tate_model_sixtopics')

In [ ]:
#Reducing the topics to 6 because it had the highest coherence score
topic_model.reduce_topics(documents, nr_topics=6)

In [ ]:
tm_nolemma = topic_model.get_topic_info()

tm_nolemma

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5030,-1_money_life_man_real,"[money, life, man, real, work, men, jail, guys...",[with one click get thousands of new_qualified...
1,0,4342,0_white_trump_jail_country,"[white, trump, jail, country, man, matrix, tru...",[first they come for us . coming for all of yo...
2,1,1015,1_ai_machines_bitcoin_replace,"[ai, machines, bitcoin, replace, money, machin...",[great_painters and heroes_alike and look back...
3,2,920,2_women_men_man_woman,"[women, men, man, woman, pain, life, children,...","[if you look at any superhero , his life is ha..."
4,3,109,3_inside_unfair_advantage_emergency_meeting_ta...,"[inside, unfair_advantage, emergency_meeting, ...",[an exclusive_stream for people who are inside...
5,4,65,4_fire_blood_plastic_vitamins_vitamin,"[fire_blood, plastic, vitamins, vitamin, suppl...",[if your notice that today 's emergency knee h...

## Visulializing Topics

In [ ]:
topic_model.get_topic(4)

[('fire_blood', 1.0052879224342626),
 ('plastic', 0.8955360675161769),
 ('vitamins', 0.8149219907387661),
 ('vitamin', 0.8061597529701643),
 ('supplement', 0.7770442851984737),
 ('micro_plastics', 0.6943013286995184),
 ('tastes', 0.6896838728093585),
 ('taste', 0.6337590438911538),
 ('yellow', 0.6311274447973504),
 ('amino_acids', 0.6121505012733879),
 ('flavoring', 0.596072307097833),
 ('vitamin_b', 0.5779955660006053),
 ('scoop', 0.5775573255066698),
 ('supplements', 0.5736125188167674),
 ('meat', 0.5722414856030572)]

In [ ]:
topic_model.visualize_barchart()

In [ ]:
topic_model.visualize_hierarchy()

In [ ]:
topic_model.visualize_topics()

In [ ]:
#50
topic_model.get_representative_docs(topic=4)

["if your notice that today 's emergency knee has been super high energy . it 's both to you by fire_blood . it is . in fact , the best thing about fire_blood is how yellow it makes your piss . you know that ? have you noticed ? make sure piss super yellow . fire makes a piss yellow . like a man , manly yellow , piss . none of that clear gay little girl pissed man fist . and the reason for that is very simple . we have all of the vitamins minerals and amino_acids , the body you can need and once to give me scoop of fire_blood . and like a man , evade , excessive . body the god of person is gon na take a supplement which tastes_disgusting with those slavery whatsoever all or you kinda something that tastes like cookie_crumble , and your peas do n't even yellow because there 's only a little_bit of vitamins in it .",
 "and the reason for that is very simple . we have all of the vitamin minerals and amino_acids , the body can need and once the union scoop fire . and like a man , made it excessive . but the kind of person is gon na take a supplement which tastes_disgusting with those slavery whatsoever or for you it tastes like cookie_crumble , and your peas got even yellow because there 's only a little_bit of vitamins in it . oh , i 've only got my daily recommended allocation of viper mutual . i 'm scared of my pee out too many vitamins heard a bumper will get now me to being wasteful . i do n't want whether to come into the gym and beat me fucking k. fire makes a piss quite yellow . like a man , manly yellow piss . none of that clear water day little girl pissed man fist . and the reason for that is it 's very simple .",
 "buy fire_blood doc . go to fire mister cigarettes . go to top_g dot_com . buy fire_blood . it tastes_disgusting . and then by a y u gay t_shirt . guys . fire_blood is absolutely horrible . it 's very hard to consume because it tastes terrible horrible . top_g dot_com by fire_blood . it tastes like ass . fizzy walter . fire makes are piss bright yellow . like a man manly yellow this . none of that clear water gay little girl pissed . man fist . and the reason for that is very simple . we have all of the vitamins news minerals and amino_acids , the body can need and once convenient scoop of fire_blood . and like a man , made it excessive . money the god of person who 's gon na take a supplement which tastes_disgusting with those slavery whatsoever or are you feed it tastes like cookie_crumble ."]

# Creating DF for each topic with all its related snippets and its corresponding video name

### Essential for the qualitative analysis

In [ ]:
#Getting doc info
docs_info = topic_model.get_document_info(documents)

In [ ]:
#Getting all doc info for topic 0
topic_0_docs = docs_info[docs_info['Topic'] == 0]

#Sort the topics by probabbility
df_sorted = topic_0_docs.sort_values(by='Probability', ascending=False)
df_sorted

In [ ]:
#Creating a function to gather all the topic snippets
# n is the number of snippets to sample
#Min_prob is the min probability threshold
#Seed is to keep it reproducable
def sample_snippets_by_topic(docs_info, topic_number=None, n=10, min_prob=0.0, seed=42):
    random.seed(seed)
    #Making a copy of the input data frame so the original doesnt change
    df = docs_info.copy()

    if topic_number is not None:
        #Keep only the rows with the corresponding topic number
        df = df[df['Topic'] == topic_number]
    #keeps rows with the correct probability
    df = df[df['Probability'] >= min_prob]

    #Randomly sample a set of rows
    sample_indices = random.sample(list(df.index), min(n, len(df)))

    #Return the randomly sampled rows with only these columns as a DF and reset the index
    return df.loc[sample_indices][['Document', 'Topic', 'Probability']].reset_index(drop=True)

In [ ]:
#Making a function to make the video title to text snippet
def vid_matching(text):
  #Grabbing the rows where the text matches exactly
  matches = chunked_df[chunked_df['bigram_nolemmatext'] == text]
  #Grabbing the video id from the the row
  video = matches['doc_id'].iloc[0]
  #returning video name
  return video

In [ ]:
#Applying the sample function
sample = sample_snippets_by_topic(docs_info, topic_number=0, n=35, min_prob=0.3)

In [ ]:
#Looking at example
sample.iloc[34]['Document']

"count the black people because i just see white people cheering . not only are they enduring this . not only are they being forced to suffer this . no . they 're happy about this . they 're entertained by this . they 're like , yeah . yeah . yeah . do it . do it . so over . islam is not ruining your countries . the invaders are n't ruining your countries . these people are ruining your countries . these people . the traders , your ... the people who have betrayed you . this is why your countries are over and they 're gon na be conquered because power vacuums must be filled . and we 've realized that there 's no masculine resistance . we 're just gon na come and take your all your shit . america 's a rich country . they must defend it really well . no . nobody defends it . a too_busy drinking wine piss from a drag queen ? cool ."

In [ ]:
#Grabbing the df for topic 3
topic_3 = sample_snippets_by_topic(docs_info, topic_number=3, n=35, min_prob=0.3)

#Adding the video name column to DF
topic_3['Video'] = topic_3['Document'].apply(vid_matching)

In [ ]:
#Saving topic list as a csv file
file_path = '/content/drive/MyDrive/Emergency_Meeting_Deepgram/topic_3.csv'
topic_3.to_csv(file_path, index=False)

# Looking at the number of snippets per video per topic

In [ ]:
#Reading in the chunked df
file_path = '/content/drive/MyDrive/Emergency_Meeting_Deepgram/chunked_df.csv'
chunked_df = pd.read_csv(file_path)

In [ ]:
#Building list of documents
documents = chunked_df['bigram_nolemmatext'].tolist()

In [ ]:
#Creating a dictionary to count the video
videos = chunked_df['doc_id'].unique()

result = {item: 0 for item in videos}

In [ ]:
#Get topic assignments for every document
docs_info = topic_model.get_document_info(documents)

#Chosing the topic to look at
topic_list = docs_info[docs_info['Topic'] == 2]['Document']

In [ ]:
#Function count the number of snippets per video
def matching(text):
  matches = chunked_df[chunked_df['bigram_nolemmatext'] == text]
  video = matches['doc_id'].iloc[0]

  for video in matches['doc_id']:
        result[video] = result.get(video, 0) + 1

  return result

In [ ]:
#running the function othe topic list
for doc in topic_list:
  matching(doc)

In [ ]:
#Number of snippets per video for topic 2
sorted_scores = dict(sorted(result.items(), key=lambda x: x[1], reverse=True))
sorted_scores

{'episode-76-gyal-dem.txt': 77,
 'episode-14.txt': 51,
 'episode-5-family-friends.txt': 36,
 'war-smiles.txt': 34,
 'episode-95-100k-party.txt': 30,
 'em-battlegrounds.txt': 29,
 'episode-35-mind-aikido.txt': 29,
 'episode-85-the-portal.txt': 25,
 'episode-87-were-so-back.txt': 23,
 'episode-88-back-to-reality.txt': 23,
 'episode-86-the-fate-of-america.txt': 22,
 'episode-15.txt': 21,
 'episode-90-happy-birthday-to-the-real-world.txt': 20,
 'episode-7-the-master-plan.txt': 19,
 'episode-73-keep-it-simple.txt': 19,
 'episode-78-overton-window.txt': 18,
 'episode-92-in-the-trenches.txt': 18,
 'episode-93-me-too.txt': 18,
 'episode-91-case-dismissed.txt': 17,
 'episode-52-do-you-have-a-sword.txt': 16,
 'episode-80-why-you-lose.txt': 16,
 'episode-100-tate-for-prime-minister.txt': 16,
 'episode-36-smackdown.txt': 15,
 'episode-81-uptober.txt': 15,
 'episode-99-2024-time-vacuum.txt': 15,
 'yeeha.txt': 14,
 'episode-47-positive-orgones.txt': 14,
 'episode-48-unfair-advantage.txt': 14,
 'episode-60-coup-attempt.txt': 14,
 'the-matrix-attacks..txt': 12,
 'weve-only-just-begun.txt': 12,
 'episode-4-the-origins-of-wudan.txt': 12,
 'counter-attack.txt': 11,
 'episode-53-the-future-of-europe-with-thierry-baudet.txt': 11,
 'episode-39-warriors.txt': 10,
 'episode-63-collapse.txt': 10,
 'episode-97-direct-democracy.txt': 10,
 'episode-30-warning-a-heros-year-is-here.txt': 9,
 'episode-49-morning-blessings.txt': 9,
 'episode-75-bbc-special.txt': 9,
 'episode-3-the-41-commandments-of-tate.txt': 8,
 'episode-34-clown-world.txt': 7,
 'episode-21-imploding-influence.txt': 6,
 'episode-40-cannot-kill-an-idea.txt': 6,
 'episode-79-positive-energy.txt': 6,
 'episode-8-awakened-warrior.txt': 5,
 'no-name.txt': 5,
 'episode-31-new-years-eve.txt': 5,
 'episode-32-roadhouse.txt': 5,
 'episode-57-presidential-debate-live.txt': 5,
 'episode-89-gear-up.txt': 5,
 'episode-98-go-time.txt': 5,
 'episode-18.txt': 4,
 'episode-38-ai-is-liberal.txt': 4,
 'episode-6-welcome-to-the-real-world.txt': 3,
 'episode-26-.txt': 3,
 'episode-27-mind-poison.txt': 3,
 'episode-42-the-oscars.txt': 3,
 'episode-44-black-swan.txt': 3,
 'episode-46-white-people.txt': 3,
 'episode-50-cowardice.txt': 3,
 'episode-69-hard-talk.txt': 3,
 'episode-72-destinations.txt': 3,
 'episode-82-huge-announcement.txt': 3,
 'episode-28-the-resistance.txt': 2,
 'episode-62-huge-case-update.txt': 2,
 'episode-74-retards.txt': 2,
 'episode-96-lawfare-breakdown.txt': 2,
 'episode-22-the-grand-adventure.txt': 1,
 'episode-23-you-dont-have-time.txt': 1,
 'episode-25-the-right-choice.txt': 1,
 'episode-33-the-chaos-is-here.txt': 1,
 'episode-41-lockdown.txt': 1,
 'episode-43-reality-was-lost.txt': 1,
 'episode-45-council-wars.txt': 1,
 'episode-56-crypto-culture.txt': 1,
 'episode-59-three-lives.txt': 1,
 'episode-66-slanderous-lies.txt': 1,
 'episode-67-infringement.txt': 1,
 'episode-71-holy-fuck.txt': 1,
 'episode-84-im-here.txt': 1,
 'the-dam-of-censorship-is-breaking.txt': 0,
 'live-from-jail.txt': 0,
 'episode-17.txt': 0,
 'episode-20-dystopian-destruction.txt': 0,
 'episode-24-social-media-alert.txt': 0,
 'episode-29-merry-christmas.txt': 0,
 'episode-37-iron-curtain.txt': 0,
 'hard-to-kill.txt': 0,
 'episode-54-trump-verdict.txt': 0,
 'episode-55-plastic-balls.txt': 0,
 'episode-58-tristans-big-british-broadcast.txt': 0,
 'episode-61-daddy-doesnt-pull-out.txt': 0,
 'episode-64-beacons-of-hope.txt': 0,
 'episode-68-cheat-codes.txt': 0,
 'episode-70-presidential-debate-live-round-2.txt': 0,
 'episode-77-october-giveaways.txt': 0,
 'episode-83-wild-ride.txt': 0,
 'episode-94-south-korean-bbq.txt': 0}